ecom/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls'), name="shop")
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path

from .views import home, ProductDetail, add_to_cart, remove_from_cart, OrderSummary, remove_single_item_from_cart, CheckOut, Payment, Payment_aproved, add_cupon

app_name="shop"

urlpatterns = [
    path('', home.as_view(), name="home"),

    path('order_summary/', OrderSummary.as_view(), name='order_summary'),

    path('checkout/', CheckOut.as_view(), name="checkout" ),
    path('payment/<payment_option>/', Payment.as_view(), name='payment'),

    path('payment_aprove/', Payment_aproved.as_view(), name="payment_aprove"),

    path('detail/<slug>/', ProductDetail.as_view(), name="detail"),
    path('add_to_cart/<slug>/', add_to_cart, name="add_to_cart"),
    path('remove_from_cart/<slug>/', remove_from_cart, name="remove_from_cart"),
    path('remove_single/<slug>/', remove_single_item_from_cart, name="remove_single"),

    path('add_cupon/', add_cupon, name="add_cupon"),
]

shop/models.py
from django.db import models
from django.shortcuts import reverse
# Create your models here.

CATEGORY_CHOICES = (
    ('S','Shirt'),
    ('SW','Sport wear'),
    ('OW','Outwear')
)

LABEL_CHOICES = (
    ('P','primary'),
    ('D','danger'),
    ('S','secondary')
)

class Device(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class User(models.Model):
    device = models.CharField(max_length=100)
    first_name= models.CharField(max_length=150, blank=True, null=True)
    last_name= models.CharField(max_length=150, blank=True, null=True)
    email= models.EmailField(max_length=250, null=True, blank=True)
    phone= models.IntegerField(blank=True, null=True)
    address= models.CharField(max_length=250, blank=True, null=True)
    localidad= models.CharField(max_length=150, blank=True, null=True)
    zip_code= models.IntegerField(blank=True, null=True)

    def __str__(self):
        if self.first_name:
            return f'{self.first_name} {self.last_name}'
        else:
            return self.device

class Item(models.Model):
    title = models.CharField(max_length=150)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()

    def __str__(self):
        return self.title

    def get_abslute_url(self):
        return reverse('shop:detail', kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse('shop:add_to_cart', kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse('shop:remove_from_cart', kwargs={
            'slug': self.slug
        })

class OrderItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity}, {self.item}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        else:
            return self.get_total_item_price()

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    items = models.ManyToManyField(OrderItem)

    start_date = models.DateTimeField(auto_now_add=True)

    ordered_date = models.DateTimeField()

    ordered = models.BooleanField(default=False)

    payment = models.ForeignKey('Payments', on_delete=models.SET_NULL, blank=True, null=True)

    cupon = models.ForeignKey('Cupon', on_delete=models.SET_NULL, blank=True, null=True)

    received = models.BooleanField(default=False)

    def __str__(self):
        if self.user.first_name:
            return self.user.first_name
        else:
            return self.user.device

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()

        if self.cupon:
            total -= self.cupon.amount
        return total

class Payments(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if self.user.first_name:
            return self.user.first_name
        else:
            return self.user.device

class Cupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code

shop/forms.py
from django import forms

PAYMENT_CHOICES = (
    ('MP', 'Mercado_Pago'),
    ('P', 'Paypal')
)

class CheckOutForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Juan',
        'class': 'form-control'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'fernandez',
        'class': 'form-control'
    }))
    email = forms.EmailField(required=False, widget=forms.TextInput(attrs={
        'placeholder':'Email@email.com',
        'class': 'form-control'
    }))
    phone = forms.IntegerField(widget=forms.TextInput(attrs={
        'placeholder':'11',
        'class': 'form-control'
    }))
    address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Rivadavia 17000',
        'class': 'form-control'
    }))
    localidad = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Morón',
        'class': 'form-control'
    }))
    zip_code = forms.IntegerField(widget=forms.TextInput(attrs={
        'placeholder':'1708',
        'class': 'form-control'
    }))
    payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_CHOICES)

class CuponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Promo code',
        'aria-label': 'Recipient\'s username',
        'aria-describedby': 'basic-addon2'
    }))

shop/views.py
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, View, ListView, DetailView
from .models import Item, Order, OrderItem, Device, User, Payments, Cupon
from django.utils import timezone
from django.shortcuts import redirect

from .forms import CheckOutForm, CuponForm
# Create your views here.

class home(ListView):
    model=Item
    template_name='shop/home-page.html'
    paginate_by = 10
    # def get(self, request, *args, **kwargs):
    #     device = request.COOKIES['device']
    #     print('device: ', device)
    #     return render(request, 'shop/index.html')

class OrderSummary(View):
    def get(self, request, *args, **kwargs):

        device = request.COOKIES['device']
        print('MyDevide: ', device)

        context=None
        user = None
        try:
            user = User.objects.get(device=device)
            print('user: ', user.device, user.email)
        except:
            pass

        if (user == None):
            user = User.objects.create(device=device)

        try:
            order = Order.objects.get(user=user, ordered=False)

            context={
                'object': order
            }

            return render(request, 'shop/order_summary.html', context)
        except ObjectDoesNotExist:
            messages.error(request, 'You have not an active order')
            return redirect('/')

    
class ProductDetail(DetailView):
    model=Item
    template_name='shop/product-page.html'

class CheckOut(View):
    def get(self, request, *args, **kwargs):

        device = request.COOKIES['device']
        order = None
        user = None
        try:
            user = User.objects.get(device=device)
        except:
            pass
        try:
            order = Order.objects.get(user=user, ordered=False)
            
            form = CheckOutForm()
            context = {
                'form':form,
                'order': order,
                'cuponform':CuponForm()
            }

            return render(request, 'shop/checkout-page.html', context)
        
        except ObjectDoesNotExist:
            messages.info(request, 'You have not an active order.')
            return redirect('shop:checkout')

        
    
    def post(self, request, *args, **kwargs):
        form = CheckOutForm(request.POST or None)
        print(request.POST)

        device = request.COOKIES['device']

        user = None
        if form.is_valid():
            print(form.cleaned_data)
            print('valid form')
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            email = form.cleaned_data.get('email')
            phone = form.cleaned_data.get('phone')
            address = form.cleaned_data.get('address')
            localidad = form.cleaned_data.get('localidad')
            zip_code = form.cleaned_data.get('zip_code')
            payment_option = form.cleaned_data.get('payment_option')
            
            try:
                user = User.objects.filter(device=device).update(
                    first_name = first_name,
                    last_name = last_name,
                    email = email,
                    phone = phone,
                    address = address,
                    localidad = localidad,
                    zip_code = zip_code,
                )
            except:
                pass
            
            if payment_option == 'P':
                return redirect('shop:payment', payment_option="Paypal")
            elif payment_option =='MP':
                return redirect('shop:payment', payment_option="Mercado_Pago")
            else:
                messages.warning(request, "Invalid payment option.")
                return redirect('shop:checkout')    
        else:
            messages.warning(request, 'Invalid form.')
            return redirect('shop:checkout')

class Payment(View):
    def get(self, request, *args, **kwargs):
        device = request.COOKIES['device']

        context=None
        user = None
        try:
            user = User.objects.get(device=device)
        except:
            pass

        #order
        order = Order.objects.get(user=user, ordered=False)
        total = order.get_total()
        if user and order.user.first_name:
            return render(request, 'shop/payment.html', {'total':total, 'order':order})
        else:
            messages.error(request, 'JYou have not added you information.')
            return redirect('shop:checkout')

class Payment_aproved(View):
    def get(self, request, *args, **kwargs):
        device = request.COOKIES['device']
        user = None
        amount = None
        try:
            user = User.objects.get(device=device)
        except:
            messages.error(request,'Error validating your payment. Please contact us.')
            return redirect('shop:home')
        if user:
                
            order = Order.objects.get(user=user, ordered=False)
            amount = order.get_total()

            #create the payment
            payment = Payments()
            payment.user = user
            payment.amount = amount
            payment.save()

            #Clear order items
            order_items = order.items.all()
            order_items.update(ordered=True)
            for item in order_items:
                item.save()

            #assign the payment to the order
            order.ordered = True
            order.payment = payment
            order.save()
    
            messages.success(request,'Payment successfully.')

            return redirect('shop:home')

        else:
            messages.error(request,'Error validating your payment. Please contact us.')
            return redirect('shop:home')
        


def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug = slug)


    device = request.COOKIES['device']
    print('devide: ', device)

    user = None
    try:
        user = User.objects.get(device=device)
    except:
        pass

    if (user == None):
        user = User.objects.create(device=device)
    

    complete_user = {'device':user.device}

    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user = user,
        ordered=False,
        
    )

    order_qs = Order.objects.filter(user=user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        #check if the order item is in the order
        if order.items.filter(item__slug = item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, 'One more item added to your cart.')
            return redirect('shop:order_summary')
        else:
            order.items.add(order_item)  
            messages.info(request, 'item added to your cart.')
            return redirect('shop:order_summary')
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user = user, ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request, 'item added to your cart.')

        return redirect('shop:order_summary')


def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug = slug)

    device = request.COOKIES['device']
    print('devide: ', device)

    user = None
    try:
        user = User.objects.get(device=device)
    except:
        pass

    order_qs = Order.objects.filter(user=user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        #check if the order item is in the order
        if order.items.filter(item__slug = item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user = user,
                ordered=False,
                
            )[0]
        
            order.items.remove(order_item) 

            messages.info(request, 'item removed from your cart.')

            return redirect('shop:order_summary')

        else:
            #add a message sayin the user doesnt have an order
            messages.info(request, 'item is not in your cart.')
            return redirect('shop:detail', slug=slug)    
    else:
        #add a message sayin the user doesnt have an order
        messages.info(request, 'You have not an active order.')
        return redirect('shop:detail', slug=slug)


def remove_single_item_from_cart(request, slug):
    item = get_object_or_404(Item, slug = slug)

    device = request.COOKIES['device']
    print('devide: ', device)

    user = None
    try:
        user = User.objects.get(device=device)
    except:
        pass

    order_qs = Order.objects.filter(user=user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        #check if the order item is in the order
        if order.items.filter(item__slug = item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user = user,
                ordered=False,
                
            )[0]

            if order_item.quantity > 1:
                order_item.quantity -= 1    
                order_item.save()
                
            else:
                order.items.remove(order_item)
        
            messages.info(request, 'Item quantity updated.')

            return redirect('shop:order_summary')

        else:
            #add a message sayin the user doesnt have an order
            messages.info(request, 'item is not in your cart.')
            return redirect('shop:detail', slug=slug)    
    else:
        #add a message sayin the user doesnt have an order
        messages.info(request, 'You have not an active order.')
        return redirect('shop:detail', slug=slug)


def get_cupon(request, code):
    try:
        cupon = Cupon.objects.get(code=code)
        return cupon

templates/shop/home-page.html
{% extends 'shop/base.html' %}




  {% block carousel %}

      <!--Carousel Wrapper-->
      <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

        <!--Indicators-->
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-1z" data-slide-to="1"></li>
          <li data-target="#carousel-example-1z" data-slide-to="2"></li>
        </ol>
        <!--/.Indicators-->

        <!--Slides-->
        <div class="carousel-inner" role="listbox">

          <!--First slide-->
          <div class="carousel-item active">
            <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg'); background-repeat: no-repeat; background-size: cover;">

              <!-- Mask & flexbox options-->
              <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

                <!-- Content -->
                <div class="text-center white-text mx-5 wow fadeIn">
                  <h1 class="mb-4">
                    <strong>Learn Bootstrap 4 with MDB</strong>
                  </h1>

                  <p>
                    <strong>Best & free guide of responsive web design</strong>
                  </p>

                  <p class="mb-4 d-none d-md-block">
                    <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                      written versions
                      available. Create your own, stunning website.</strong>
                  </p>

                  <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                    free tutorial
                    <i class="fas fa-graduation-cap ml-2"></i>
                  </a>
                </div>
                <!-- Content -->

              </div>
              <!-- Mask & flexbox options-->

            </div>
          </div>
          <!--/First slide-->

          <!--Second slide-->
          <div class="carousel-item">
            <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg'); background-repeat: no-repeat; background-size: cover;">

              <!-- Mask & flexbox options-->
              <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

                <!-- Content -->
                <div class="text-center white-text mx-5 wow fadeIn">
                  <h1 class="mb-4">
                    <strong>Learn Bootstrap 4 with MDB</strong>
                  </h1>

                  <p>
                    <strong>Best & free guide of responsive web design</strong>
                  </p>

                  <p class="mb-4 d-none d-md-block">
                    <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                      written versions
                      available. Create your own, stunning website.</strong>
                  </p>

                  <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                    free tutorial
                    <i class="fas fa-graduation-cap ml-2"></i>
                  </a>
                </div>
                <!-- Content -->

              </div>
              <!-- Mask & flexbox options-->

            </div>
          </div>
          <!--/Second slide-->

          <!--Third slide-->
          <div class="carousel-item">
            <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg'); background-repeat: no-repeat; background-size: cover;">

              <!-- Mask & flexbox options-->
              <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

                <!-- Content -->
                <div class="text-center white-text mx-5 wow fadeIn">
                  <h1 class="mb-4">
                    <strong>Learn Bootstrap 4 with MDB</strong>
                  </h1>

                  <p>
                    <strong>Best & free guide of responsive web design</strong>
                  </p>

                  <p class="mb-4 d-none d-md-block">
                    <strong>The most comprehensive tutorial for the Bootstrap 4. Loved by over 500 000 users. Video and
                      written versions
                      available. Create your own, stunning website.</strong>
                  </p>

                  <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                    free tutorial
                    <i class="fas fa-graduation-cap ml-2"></i>
                  </a>
                </div>
                <!-- Content -->

              </div>
              <!-- Mask & flexbox options-->

            </div>
          </div>
          <!--/Third slide-->

        </div>
        <!--/.Slides-->

        <!--Controls-->
        <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
        <!--/.Controls-->

      </div>
      <!--/.Carousel Wrapper-->

  {% endblock %}


  {% block content %}

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">All
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Shirts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Sport wears</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Outwears</a>
          </li>

        </ul>
        <!-- Links -->

        <form class="form-inline">
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          </div>
        </form>
      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

      <!--Grid row-->
      <div class="row wow fadeIn">

        {% for item in object_list %}

          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <!-- <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top"
                  alt=""> -->

                <img src="{{item.image.url}}" class="card-img-top" >

                <a href="{{item.get_abslute_url}}"  >
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{item.get_category_display}}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{item.get_abslute_url}}" class="dark-grey-text">{{item.title}}
                      <span class="badge badge-pill {{item.get_label_display}}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>$
                    {% if item.discount_price %}
                      {{item.discount_price}}
                    {% else %}
                      {{item.price}}
                    {% endif %}
                  </strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->
        
        {% endfor %}

      </div>
      <!--Grid row-->

    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->

    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        {% if page_obj.has_previous %}
          <!--Arrow left-->
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
        {% endif %}
        

        <li class="page-item active">
          <a class="page-link" href="?page={{page_obj.number}}">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            <span class="sr-only">(current)</span>
          </a>
        </li>

        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}
    <!--Pagination-->


  {% endblock %}

     

templates/shop/list.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if object_list %}

        {% for item in object_list %}
            <h2>{{item}}</h2>
        {% endfor %}

    {% endif %}
</body>
</html>

templates/shop/order_summary.html
{% extends 'shop/base.html' %}

{% block content %}

<div class="" style="margin-top: 80px;" >
    <div class="table-responsive text-nowrap">

        <h2>Order summary</h2>
    
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Item title</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total item price</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in object.items.all %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{obj.item.title}}</td>
                    <td>${{obj.item.price}}</td>
                    <td> 
                        <a href="{% url 'shop:remove_single' obj.item.slug %}" ><i class="fas fa-minus mr-2"></i></a> 
                        {{obj.quantity}}
                        <a href="{% url 'shop:add_to_cart' obj.item.slug %}" > <i class="fas fa-plus ml-2"></i> </a>
                    </td>
                    <td>
                        {% if obj.item.discount_price %}
                            ${{ obj.get_total_discount_item_price }}
                            <span class="badge badge-primary" >Saving ${{obj.get_amount_saved}}</span>
                        {% else %}
                            {{obj.get_total_item_price}}
                        {% endif %}
                        <a href="{% url 'shop:remove_from_cart' obj.item.slug %}" > 
                            <i class="fas fa-trash float-right"></i> 
                        </a>
                    </td>
                </tr>
            {% empty %}
            <tr>
                <td colspan="5" >Your cart is empty</td>
            </tr>

            <tr>
                <td colspan="5" >
                    <a class="btn btn-primary float-right" href="{% url 'shop:home' %}" >Contunue shoping</a>
                </td>
            </tr>

            {% endfor %}

            {% if object.cupon %}
                <tr>
                    <td colspan="4" ><b>Coupon</b></td>
                    <td><b>-${{object.cupon.amount}}</b></td>
                </tr>
            {% endif %}
                
            {% if object.get_total %}

                <tr>
                    <td colspan="4" ><b>Total</b></td>
                    <td><b>${{object.get_total}}</b></td>
                </tr>

                <tr>
                    <td colspan="5" > 
                        <a class="btn btn-warning float-right ml-2" href="{% url 'shop:checkout' %}"  >Proceed to checkout</a> 
                        <a class="btn btn-primary float-right" href="{% url 'shop:home' %}" >Contunue shoping</a>
                    </td>
                    
                </tr>
            {% endif %}

            </tbody>
        </table>
    
    </div>
</div>

{% endblock %}